// system
export const SET_SETTINGS = "SET_SETTINGS"
export const SET_REPORT_USERNAME = "SET_REPORT_USERNAME"
export const SET_UPDATE_USER = "SET_UPDATE_USER"
export const SET_WORKING_TIME_OF_USER = "SET_WORKING_TIME_OF_USER"
export const REMOVE_WORKING_TIME_OF_USER = "REMOVE_WORKING_TIME_OF_USER"
